### ISSUE TITLE
Parser combinators are not thread-safe

### ISSUE THREAD

**Issue by scabug** [scala/scala-parser-combinators#321]
JSON.parseFull or parseRaw randomly fails with NPE.  In order to get the stacktrace, one must use -Xint flag.  It works fine most of the time and randomly fails.  When I run a simple script that parses JSON.parseFull("{\"hello\": \"dude\"}"), when run in a loop 10K times, it fails a few times during the run (again, randomly).  Below is the stacktrace...

java.lang.NullPointerException: null
	at scala.util.parsing.combinator.Parsers$NoSuccess.<init>(Parsers.scala:132) ~[scala-library.jar:na]
	at scala.util.parsing.combinator.Parsers$Failure.<init>(Parsers.scala:159) ~[scala-library.jar:na]
	at scala.util.parsing.combinator.Parsers$$anonfun$acceptIf$1.apply(Parsers.scala:499) ~[scala-library.jar:na]
...

**Comment by SethTisue** [comment]
with any luck, fixed by #234
