### ISSUE TITLE
ParseResult.toString results in java.util.NoSuchElementException: head of empty list

### ISSUE THREAD

**Issue by tormeh** [scala/scala-parser-combinators#46]
ParseResult.toString results in java.util.NoSuchElementException: head of empty list
Relevant code:

``` scala
val ast = progParser(new TokenReader(in))
println(ast.toString) // <-------------- Here is where things go wrong
                               //println(ast.get.toString) works fine


class TokenReader(in:List[Token]) extends Reader[Elem]
  {
    def atEnd:Boolean = in.isEmpty
    def first:Elem = in.head
    def pos:Position = in.head.pos;
    def rest = new TokenReader(in.tail)
  }

def progParser: Parser[List[Definition]] = (paddedDefParser.+) <~ eofParser

class Expression()
case class Definition(val leftside:DefLhs, val rightside:DefRhs) extends Expression
```

Error + top of stacktrace:

```
[error] (run-main-8) java.util.NoSuchElementException: head of empty list
java.util.NoSuchElementException: head of empty list
    at scala.collection.immutable.Nil$.head(List.scala:420)
    at scala.collection.immutable.Nil$.head(List.scala:417)
    at fumurtCompiler.FumurtParser$TokenReader.pos(Parser.scala:88)
    at scala.util.parsing.combinator.Parsers$Success.toString(Parsers.scala:154)

```

**Comment by Philippus** [comment]
Would it be (still) possible to create a minimal self-contained failing test?

**Comment by SethTisue** [comment]
I suggest we close this, since we don't have a minimization.

**Comment by Philippus** [comment]
Closing this, if we have a minimized test feel free to re-open.
