### ISSUE TITLE
Release version 2.3.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#510]
my first attempt failed — I'll try again. I deleted the release and tag, which is okay because no artifacts were published

* [x] tag: https://github.com/scala/scala-parser-combinators/releases/tag/v2.3.0
* [x] release build: https://github.com/scala/scala-parser-combinators/actions/runs/4813947057
* [x] artifacts on Maven Central https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_3/2.3.0/
* [x] reset version policy to `BinaryAndSourceCompatible`: #515

**Comment by SethTisue** [comment]
the failure log is at 
https://github.com/scala/scala-parser-combinators/actions/runs/4618060247/jobs/8165036323

it shows

```
2023-04-05 11:42:01.810Z  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:108)
2023-04-05 11:42:03.381Z error [Sonatype] 
wvlet.airframe.http.HttpClientException: [401: Unauthorized]
	at wvlet.airframe.http.HttpClientException$.requestFailure(HttpClientException.scala:67)
	at wvlet.airframe.http.HttpClientException$.classifyHttpResponse(HttpClientException.scala:113)
	at wvlet.airframe.http.HttpClient$.$anonfun$defaultHttpClientRetry$1(HttpClient.scala:382)
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:272)
	at wvlet.airframe.control.Retry$RetryContext.runWithContext(Retry.scala:257)
	at wvlet.airframe.http.client.URLConnectionClient.send(URLConnectionClient.scala:64)
	at wvlet.airframe.http.client.URLConnectionClient.get(URLConnectionClient.scala:165)
	at xerial.sbt.sonatype.SonatypeClient.stagingRepositoryProfiles(SonatypeClient.scala:110)
```

I'm not sure what to make of this, We just rolled a release a few months ago and this didn't happen.

**Comment by SethTisue** [comment]
The secrets at https://github.com/scala/scala-parser-combinators/settings/secrets/actions date back to September 2021. I guess I'll try regenerating them and see if that helps.

**Comment by SethTisue** [comment]
replacing the PGP key didn't help, but then it was a Sonatype login issue, so that makes sense

but the Sonatype login info hasn't changed 🤔 

regardless, I re-added that login info and re-ran the job

and it seems to be working now 🤷
