### ISSUE TITLE
NullPointerException in PagedSeq/StreamReader

### ISSUE THREAD

**Issue by alanbur** [scala/scala-parser-combinators#70]
I'm getting a NullPointerException when using the Scala JSON parser on a stream. If I read the contents of the stream into a String and parse that instead, then it completes with no error. That suggests it's not an error in the JSON parser, it is in the StreamReader and/or PagedSeq collection classes. The stack trace is:

````
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.immutable.PagedSeq.slice(PagedSeq.scala:192)
	at scala.collection.immutable.PagedSeq.slice(PagedSeq.scala:205)
	at scala.util.parsing.input.StreamReader.rest(StreamReader.scala:56)
	at scala.util.parsing.input.StreamReader.rest(StreamReader.scala:48)
	at scala.util.parsing.combinator.Parsers$$anonfun$acceptIf$1.apply(Parsers.scala:599)
	at scala.util.parsing.combinator.Parsers$$anonfun$acceptIf$1.apply(Parsers.scala:597)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.applyp$1(Parsers.scala:718)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.continue$1(Parsers.scala:724)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.scala:728)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.scala:712)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.lexical.Scanners$Scanner.<init>(Scanners.scala:45)
	at scala.util.parsing.combinator.lexical.Scanners$Scanner.rest(Scanners.scala:58)
	at scala.util.parsing.combinator.lexical.Scanners$Scanner.rest(Scanners.scala:42)
	at scala.util.parsing.combinator.Parsers$$anonfun$acceptIf$1.apply(Parsers.scala:599)
	at scala.util.parsing.combinator.Parsers$$anonfun$acceptIf$1.apply(Parsers.scala:597)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Success.flatMapWithNext(Parsers.scala:143)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:234)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:237)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:249)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:217)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:882)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:882)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:881)
	at com.oracle.psarc.common.JSONParser.parseRaw(JSONParser.scala:31)
	at com.oracle.psarc.common.JSONParser.parseFull(JSONParser.scala:42)
	at com.oracle.psarc.common.PathConfig$.load(PathConfig.scala:35)
	at IndexMain$.main(IndexMain.scala:27)
	at IndexMain.main(IndexMain.scala)
````

**Comment by liskin** [comment]
Seems to be a problem in PagedSeq. StreamReader calls `seq.slice(off + 1)` after only checking that `seq.isDefinedAt(off)` (which should be okay since otherwise there would be no way to create an empty slice) and PagedSeq fails to check if addMore actually adds more. I'll try to fix PagedSeq.

**Comment by alanbur** [comment]
Thanks for such a quick fix But it appears Seth Tisue has deleted https://issues.scala-lang.org/browse/SI-9480, which I believe is the bug you submitted your pull request with the fix against...

**Comment by liskin** [comment]
Yeah, he did. Don't know why. @SethTisue, would you mind elaborating a bit? Anyway, the fix is here: https://github.com/scala/scala/pull/4753

**Comment by SethTisue** [comment]
I apologize. I messed this up. I hastily assumed this would turn out to be a parser combinators bug, and when you discovered it wasn't, I failed to register that, so I thought the original ticket had no further value.

I'll comment on the PR about our options now.

**Comment by SethTisue** [comment]
@Ichoran, all: perhaps we should deprecate PagedSeq in 2.12? Is it an obscure, special-purpose thing that probably doesn't have other clients besides scala.util.parser.combinators?

**Comment by Ichoran** [comment]
@sethtisue - I would recommend deprecating it if we can. It is a pretty weirdly-behaved collection even when it isn't throwing NPEs. I don't know its usage pattern, though.

**Comment by SethTisue** [comment]
I started a scale-language thread on the possible deprecation: https://groups.google.com/d/msg/scala-language/gq8iueZmjjg/QQGFZIZsAAAJ

**Comment by gourlaysama** [comment]
This was fixed in 2.11.8 (scala/scala#4758).

**Comment by SethTisue** [comment]
(note that it would still be nice to have https://github.com/scala/scala-parser-combinators/issues/71 addressed so that PagedSeq can be removed from Scala 2.13)

**Comment by gourlaysama** [comment]
Yes, I'm looking into what it can be replaced with.
